### ISSUE TITLE
iOS Safari choopy scrolling

### ISSUE THREAD

**Issue by oswaldoacauan** [oswaldoacauan/ghostium#6]
Add prefix `-webkit-` for `overflow-scrolling: touch;`
and the following CSS

``` css
.content {
  position: relative;
  min-height: 100%;
}
```

**NOT TESTED**

[Reference](http://stackoverflow.com/questions/12845892/ios-overflow-x-or-position-absolute-makes-scrolling-choppy)
